#!/bin/bash
#Color variables
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
PURPLE='\033[0;34m'
CYAN='\033[0;35m'
LIGHTGRAY='\033[0;36m'
NC='\033[0m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
LIGHTORANGE='\033[1;33m'
LIGHTPURPLE='\033[1;34m'
LIGHTCYAN='\033[1;35m'

#Dependencies
##prometheus 2.7.1 https://packages.debian.org/sid/prometheus
mkdir -p ~/dependencies
cd ~/dependencies

##libjs dependencies
echo -e "[${GREEN}+${NC}] Installing dependencies..."
sleep 3
wget -i libjs_dependencies.txt 
sudo apt-get -f install
sudo dpkg -i fonts-glyphicons-halflings_1.009~3.4.1+dfsg-1_all.deb
sudo dpkg -i libjs-bootstrap_3.4.1+dfsg-1_all.deb
sudo dpkg -i libjs-jquery_3.3.1~dfsg-1_all.deb
sudo dpkg -i libjs-moment_2.24.0+ds-1_all.deb
sudo dpkg -i libjs-eonasdan-bootstrap-datetimepicker_4.17.47-3_all.deb
sudo dpkg -i libjs-jquery-hotkeys_0~20130707+git2d51e3a9+dfsg-2_all.deb
sudo dpkg -i libjs-moment-timezone_0.5.23+dfsg1-1_all.deb
sudo dpkg -i libjs-mustache_2.3.2-1_all.deb
sudo dpkg -i libjs-d3_3.5.17-2_all.deb
sudo dpkg -i libjs-rickshaw_1.5.1.dfsg-2_all.deb

##node_exporter
sudo dpkg -i daemon_0.6.4-1+b2_amd64.deb
echo -e "[${GREEN}+${NC}] Installing ${GREEN}Prometheus${NC} ..."
sudo dpkg -i prometheus-node-exporter_0.13.0+ds-1+b2_amd64.deb

echo -e "[${GREEN}+${NC}] Checking prometheus status..."
sleep 2
systemctl status prometheus
